Generate a prediction with a multinomial logistic regression model using dataset generated from make_classification from sklearn family, Consider 12,500 samples, 10 features and 3 classes.

In [1]:
# Import libraries
import numpy as np
import pandas as pd
import statsmodels.api as sm

from sklearn.datasets import make_classification

In [2]:
# Load synthetic data using make_classification

X, y = make_classification(n_samples=12500, n_features=10, n_classes=3, n_informative=3, n_redundant=0, random_state=42)

In [3]:
X

array([[ 0.36023877, -1.23625119, -0.9264039 , ...,  0.80600628,
        -0.7860695 ,  1.54255115],
       [ 0.69536372, -1.44911042,  0.27984321, ...,  3.15827466,
        -0.63290907,  0.7738562 ],
       [-0.34190186,  1.5779671 ,  0.21658905, ..., -1.10025332,
        -0.77895017,  2.34602942],
       ...,
       [-1.8572541 ,  0.07733143,  0.37332212, ..., -1.18590403,
        -1.1561816 ,  0.37983032],
       [ 0.58367577,  0.56884014,  0.61548025, ..., -1.32307162,
         0.69751078, -0.40435324],
       [ 0.70843097,  1.06770197,  0.57842889, ...,  0.15795153,
         0.33623293, -2.01490529]])

In [4]:
y

array([0, 0, 2, ..., 2, 1, 0])

In [5]:
# Fit the model
X = sm.add_constant(X)

mlogit_mod = sm.MNLogit(y, X)
mlogit_res = mlogit_mod.fit()

Optimization terminated successfully.
         Current function value: 0.826218
         Iterations 7


In [6]:
print(mlogit_res.summary())

                          MNLogit Regression Results                          
Dep. Variable:                      y   No. Observations:                12500
Model:                        MNLogit   Df Residuals:                    12478
Method:                           MLE   Df Model:                           20
Date:                Wed, 22 Jun 2022   Pseudo R-squ.:                  0.2479
Time:                        22:18:43   Log-Likelihood:                -10328.
converged:                       True   LL-Null:                       -13733.
Covariance Type:            nonrobust   LLR p-value:                     0.000
       y=1       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.4074      0.027     15.195      0.000       0.355       0.460
x1             0.0261      0.024      1.096      0.273      -0.021       0.073
x2             0.0106      0.024      0.445      0.6

In [7]:
# Model Intercepts
mlogit_res.params[0]

array([ 0.40736244, -0.42644571])

In [8]:
# Use Solvers
mlogit_res_bfgs = mlogit_mod.fit(method="bfgs", maxiter=250)
print(mlogit_res_bfgs.summary())

Optimization terminated successfully.
         Current function value: 0.826218
         Iterations: 26
         Function evaluations: 27
         Gradient evaluations: 27
                          MNLogit Regression Results                          
Dep. Variable:                      y   No. Observations:                12500
Model:                        MNLogit   Df Residuals:                    12478
Method:                           MLE   Df Model:                           20
Date:                Wed, 22 Jun 2022   Pseudo R-squ.:                  0.2479
Time:                        22:18:43   Log-Likelihood:                -10328.
converged:                       True   LL-Null:                       -13733.
Covariance Type:            nonrobust   LLR p-value:                     0.000
       y=1       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.4074      0.027     1

In [9]:
# Model Intercepts
mlogit_res_bfgs.params[0]

array([ 0.40738729, -0.42644827])

In [10]:
# Use another solver
mlogit_res_powell = mlogit_mod.fit(method="powell", maxiter=250)
print(mlogit_res_powell.summary())

Optimization terminated successfully.
         Current function value: 0.826261
         Iterations: 6
         Function evaluations: 1367
                          MNLogit Regression Results                          
Dep. Variable:                      y   No. Observations:                12500
Model:                        MNLogit   Df Residuals:                    12478
Method:                           MLE   Df Model:                           20
Date:                Wed, 22 Jun 2022   Pseudo R-squ.:                  0.2479
Time:                        22:18:46   Log-Likelihood:                -10328.
converged:                       True   LL-Null:                       -13733.
Covariance Type:            nonrobust   LLR p-value:                     0.000
       y=1       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.4305      0.027     15.960      0.000       0.378     

In [11]:
# Model Intercepts
mlogit_res_powell.params[0]

array([ 0.43045519, -0.40001026])